a = input('Введите первое слово')
b = input("Введите второе слово")
a = list(a)
b = list(b)
a.sort()
b.sort()
if a == b:
    print("Введенные слова анаграммы")
else:print("Введенные слова не являются анаграммами")
print(a)
print(b)